Feature/layout
Poldyaich97/airbnb pull request #1
Opened 2021-11-26 16:08 UTC by Poldyaich97

Добавили header.
Переименовали файлы в из js в jsx

2021-11-26 16:13 UTC, chervyakovru reviewed
look at this, dude!

2021-11-26 16:13 UTC, chervyakovru commented on src/Header/Header.css
> +  width: 80%;
Ширину лучше задать в пикселях, а с помощью медиавыдажений ее менять

2021-11-26 16:13 UTC, chervyakovru commented on src/index.js
>    <React.StrictMode>
Что такое StrictMode? @Poldyaich97

2021-11-30 21:03 UTC, chervyakovru commented on src/Header/Header.css
> +  width: 80%;
Не задал?

2021-11-30 21:30 UTC, chervyakovru requested changes
Отревьюил

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  height: 80px;
Высоту задавать фиксированную не нужно. 
Высота должна зависеть от контента.

Высоту в пикселях стоит задавать только изображениям

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  margin: 0px;
Кажется, у ::before и так нет марджинов и паддингтв

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  height: 100%;
В этом нет необходимости

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  display: flex;
Это тоже не нужно. По сути внутри будут блочные элементы, а они по умолчанию друг за другом по вертикали идут

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  margin-right: 51px;
51 пиксель нехорошее число. В идеале стоит делать так, чтобы у тебя все размеры были кратны 8 или 4px. Так меньше шансов запутаться в отступах

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  margin-right: 51px;
Возможно, в дизайне и 51px. Но фронтендер это самый главный тестировщик дизайнера. И если он видит какой-то косяк, то лучше сообщить об этом дизайнеру и с ним договориться как это поправить

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  flex-basis: 15%;
Вот тут тоже не надо так. Пусть это будет картинка с заданными размерами высоты и ширины в пикселях. Только у картинок так что т делать.

Тут хоть и в процентах задано, но в медиа выражениях все равно придется менять. А так как мы договорились зафиксировать ширину контейнера, то фиксированные размеры картинки очень вписываются в эту концепцию

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  padding-bottom: 18px;
Скорее всего горизонтальные паддинги там тоже есть. Текст не должен прилипать к краям ним какой стороны

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  height: 48px;
Опять же не стоит задавать высоту. Все можно решить паддингами

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  display: flex;
Кажетсяflex тут лишний

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +#site-search {
Для css селекторов лучше всегда использовать классы, если нет причин для иного. Если у элемента есть толькоid, то лучше все равно добавит такой-же класс ему и обратиться к элементу по классу
id лучше использовать в js

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  height: 24px;
И тут ещё флекс базис и высота. Стоит убрать

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.css
> +  margin-right: 0;
Есть принципиально другой подход к добавлению отступов между элементами списка. 
Просто стоит знать, он не хуже и не лучше

.class-selector + .class-selector {
margin-left: 5px
}

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.jsx
> +            <img src={search} alt="search logo" />
alt тег имеет смысл добавлять, когда хочешь чтобы скринридер прочитал что находится на изображении.
Если отталкиваться от этой концепции, то логично предположить, что иконки нужны только зрячим. И поэтому их логичнее добавить с помощью SVG/background/:before, etc

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.jsx
> +            placeholder="Try “Miami”"
Кавычки в кавычках лучше экранировать. Либо, если используешь двойные кавычки внутри, то использовать одинарные снаружи

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.jsx
> +          <button className="search_btn">
Как ты обозначает Element из БЭМ?
block_elemebt__modificator
Или
block__element_modificator

Сейчас у тебя то так то так

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.jsx
> +          <a href="#" className="menu_links">
Element не живёт без блока. А у этой ссылки блока нет. Нужно добавить

2021-11-30 21:30 UTC, chervyakovru commented on src/Header/Header.jsx
> +        <div className="header_menu">
Лучше сделать через ul>li>a

Так семантичнее

А ещё лучше nav>li>a

2021-11-30 21:30 UTC, chervyakovru commented on src/index.js
>    <React.StrictMode>
Напиши тут ответ своими словами

2021-12-01 11:11 UTC, Poldyaich97 commented on src/index.js
>    <React.StrictMode>
Это инструмент обнаружения проблем в приложении.
В этом случае у нас будет работать именно для 8 строки.
Строгий режим активирует дополнительные проверки.

2021-12-01 13:25 UTC, Poldyaich97 commented on src/Header/Header.css
> +  width: 80%;
Задал.
1460px;

2021-12-01 13:26 UTC, Poldyaich97 commented on src/Header/Header.css
> +  height: 80px;
Убрал

2021-12-02 05:42 UTC, Poldyaich97 commented on src/Header/Header.css
> +  margin: 0px;
Убрал

2021-12-02 05:42 UTC, Poldyaich97 commented on src/Header/Header.css
> +  height: 100%;
Убрал

2021-12-02 07:13 UTC, Poldyaich97 commented on src/Header/Header.css
> +  display: flex;
Тут у меня вопрос.


Не совсем понял.
display: flex не нужен?
Они ведь в таком случае будут занимать всю ширину экрана.
либо флекс,либо инлайнблок

2021-12-02 07:13 UTC, Poldyaich97 commented on src/Header/Header.css
> +  margin-right: 51px;
исправил

2021-12-02 07:14 UTC, Poldyaich97 commented on src/Header/Header.css
> +  flex-basis: 15%;
Исправил

2021-12-02 07:16 UTC, Poldyaich97 commented on src/Header/Header.css
> +  padding-bottom: 18px;
Исправил

2021-12-02 07:16 UTC, Poldyaich97 commented on src/Header/Header.css
> +  height: 48px;
Убрал

2021-12-02 08:09 UTC, Poldyaich97 commented on src/Header/Header.css
> +  display: flex;
Убрал

2021-12-02 08:09 UTC, Poldyaich97 commented on src/Header/Header.css
> +#site-search {
поменял

2021-12-02 08:10 UTC, Poldyaich97 commented on src/Header/Header.css
> +  margin-right: 0;
Не совсем понял. этот не подходит?

2021-12-02 08:11 UTC, Poldyaich97 commented on src/Header/Header.jsx
> +            <img src={search} alt="search logo" />
поменял

2021-12-02 08:12 UTC, Poldyaich97 commented on src/Header/Header.jsx
> +          <button className="search_btn">
Изменил

2021-12-02 08:26 UTC, Poldyaich97 commented on src/Header/Header.jsx
> +        <div className="header_menu">
исправил

2021-12-02 08:39 UTC, Poldyaich97 commented on src/Header/Header.jsx
> +          <a href="#" className="menu_links">
изменил

2021-12-02 08:39 UTC, Poldyaich97 commented on src/Header/Header.jsx
> +            placeholder="Try “Miami”"
убрал

2021-12-02 08:40 UTC, Poldyaich97 commented on src/Header/Header.css
> +  height: 24px;
убрал

2021-12-03 08:45 UTC, Poldyaich97 commented on src/Header/Header.css
> +  display: flex;
готово

2021-12-05 17:11 UTC, chervyakovru commented
App.css не нужен

2021-12-05 17:13 UTC, chervyakovru commented
Файл src/Footer/facebook.svg странный

2021-12-05 17:19 UTC, chervyakovru commented
Много ошибок в консоли

![image](https://user-images.githubusercontent.com/14909082/144756577-ba8339e8-27d1-4f59-b311-2382fddec94d.png)

2021-12-05 17:20 UTC, chervyakovru commented
Шрифт не соответствует макету

![image](https://user-images.githubusercontent.com/14909082/144756602-75840e5b-ab1f-4e4a-be2a-7cd1d36d77f1.png)

2021-12-05 17:21 UTC, chervyakovru commented
Присутствует горизональный скролл

![image](https://user-images.githubusercontent.com/14909082/144756620-ab6b8c83-5a59-4fe0-a11c-c428658d0d13.png)

2021-12-05 17:23 UTC, chervyakovru commented
Нижняя граница шапки не по макету. В мекете нижняя граница задана с помощью box-shadow

![image](https://user-images.githubusercontent.com/14909082/144756650-f1d6c805-69b4-49a5-beaa-836ccbf273ed.png)
![image](https://user-images.githubusercontent.com/14909082/144756674-6482bc1d-3f49-4641-b74d-adbb66e1efb9.png)

2021-12-05 17:25 UTC, chervyakovru commented
Не стоит задавать паддинки у каждого элемента в родителе. Лучше задать один общий отступ у родителя

![image](https://user-images.githubusercontent.com/14909082/144756724-f560dbeb-faf1-45be-9304-ec513b4f0cf9.png)

2021-12-05 17:27 UTC, chervyakovru commented
Не стоит задавать ширину или высоту элемента в px. Размеры элемента должны зависеть от контента, либо задаваться в % от родителя. Исключениями являются картинки. Им указывать размеры стоит 

![image](https://user-images.githubusercontent.com/14909082/144756779-e27e69ad-1bca-4a4c-b8b3-a37e66cdde4d.png)

2021-12-05 17:31 UTC, chervyakovru commented
Вот тут все css свойства не нужны.
Ширина должна исходить от контента - от input
margin не нужен, потому что контент справа должен быть прижат к правому краю
Вертикальные паддинги должны быть у контейнера, горизонтальных быть не должно вовсе
высоту тут задавать нет смысла, она и так 100% и, опять же, должна исходить от контента
background у этого элемента не должен быть задан. В этом нет смысла

![image](https://user-images.githubusercontent.com/14909082/144756843-0572c834-a4d2-4455-8f4d-b175413963f0.png)

2021-12-05 17:35 UTC, chervyakovru commented
Вот стили для рамки вокруг инпута из макета. Нужно использовать их, а не пытаться подобрать самому

![image](https://user-images.githubusercontent.com/14909082/144757032-04410bd5-32c6-48a7-95c9-ab2e74494423.png)

2021-12-05 17:37 UTC, chervyakovru commented
Вот эти все стили лучше заменить на pos: absolute и top+ left

![image](https://user-images.githubusercontent.com/14909082/144757152-e165bf60-dab7-4284-abcd-dbf31eff403a.png)

2021-12-05 17:40 UTC, chervyakovru commented
Высоту не стоит указывать
Ширину, тут, стоило указать, но в em
padding-и не соответсвуют макету

![image](https://user-images.githubusercontent.com/14909082/144757219-2077f89b-8f08-447d-949a-3d034188b13a.png)

2021-12-05 17:45 UTC, chervyakovru commented
А вот тут ситуация - исключение)
Тут паддинги стоит задавать у каждого элемента. Это тоже относится к UX. Пользователь ожидает, что клик по всей высоте шапки будет работать как клик по ссылке. Поэтому вся высота должна быть занята ссылкой

![image](https://user-images.githubusercontent.com/14909082/144757292-b68faa37-4a0a-4881-95e4-cb30e70db335.png)

2022-01-14 19:45 UTC, closed without merging