Feature/layout
Poldyaich97/airbnb pull request #3
Opened 2022-01-16 12:32 UTC by Poldyaich97

add Reviewers

2022-01-16 13:37 UTC, chervyakovru commented
Можно убрать папку @font-face

2022-01-16 13:47 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/149662719-d679427a-3b5e-4cd1-abf2-cca2fc99e5b6.png)
![image](https://user-images.githubusercontent.com/14909082/149662746-0cbcfc67-68e5-4490-921b-bb07be740d8b.png)

Проект не запускается. Названия папок не соответствует

2022-01-16 14:17 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/149663750-3e20791e-e09e-4901-a1fe-c530a69d1655.png)

На импуте сломался шрифт

2022-01-16 14:25 UTC, chervyakovru commented
#пиксельдрочево

![image](https://user-images.githubusercontent.com/14909082/149663996-285f5b69-dc74-4733-8575-712fe3b00a7c.png)

2022-01-16 14:34 UTC, chervyakovru commented
Растровые картинки нельзя выгружать в svg формате, Они хуже адаптируются, практически не сжимаются и дольше рендерятся

2022-01-16 14:49 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/149665005-e6306f84-4df4-44c7-835c-c0d3e9fb0308.png)

Картинка уже чем колонка

2022-01-16 14:52 UTC, chervyakovru commented
Есть 2 разных рейтинга. У тебя это 1 компонент

![image](https://user-images.githubusercontent.com/14909082/149665033-e5fb891e-4bdb-46eb-a750-e442315468c0.png)

2022-01-16 14:55 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/149665171-194eb5f7-5684-4273-ba47-4b2217988d91.png)
![image](https://user-images.githubusercontent.com/14909082/149665173-bd7b1163-0c26-4531-ba4d-4a135ad08302.png)

Отличается макет от верстки

2022-01-16 15:05 UTC, chervyakovru requested changes

2022-01-16 15:05 UTC, chervyakovru commented on src/App.jsx
> +const AppMain = styled(Main)``;
Можно убрать  styled

2022-01-16 15:05 UTC, chervyakovru commented on src/App.jsx
> +const StyledStub = styled(Stub)`
Будет проще, Если Stub По умолчанию будет отображаться, а медиа выражением его скрывать на десктопе

2022-01-16 15:05 UTC, chervyakovru commented on src/App.jsx
> +const StyledStub = styled(Stub)`
Это опять же соответствует идее компонентного подхода

2022-01-16 15:05 UTC, chervyakovru commented on src/App.jsx
> +const StyledStub = styled(Stub)`
И тогда врапер будет не нужен

2022-01-16 15:05 UTC, chervyakovru commented on src/Fonts/@font-face/Demo.html
> +<!DOCTYPE html>
Этот файл не нужен

2022-01-16 15:05 UTC, chervyakovru commented on src/Footer/Footer.jsx
> +const StyledFooter = styled.div``;
styled не нужен

2022-01-16 15:05 UTC, chervyakovru commented on src/Footer/Footer.jsx
> +  margin-bottom: 16px;
margin-bottom лучше убрать, добавить flex column-gap в StyledBurger

2022-01-16 15:05 UTC, chervyakovru commented on src/Footer/Footer.jsx
> +  padding: 0;
padding лишний

2022-01-16 15:05 UTC, chervyakovru commented on src/Footer/Footer.jsx
> +  margin-right: 0;
margin-right: 0; не нужен

2022-01-16 15:05 UTC, chervyakovru commented on src/Footer/facebook.svg
> +<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
![image](https://user-images.githubusercontent.com/14909082/149663238-9c25300c-4876-407b-8b22-179953d905c5.png)
![image](https://user-images.githubusercontent.com/14909082/149663240-e004b1bb-fa65-4b9b-8d78-fee571381bd9.png)


![image](https://user-images.githubusercontent.com/14909082/149663257-d0b77d03-b345-438f-95cf-7cf3bf0f3b4f.png)


Иконки лучше выгружать одного размера - так макет будет ровным и не нужен будет подгонять отступы чтобы выглядело как на макете. А также таким образом увеличивается клиекабельная область и пользователю проще нажимать

2022-01-16 15:05 UTC, chervyakovru commented on src/Footer/footerLogo.svg
> +<svg width="21" height="22" viewBox="0 0 21 22" fill="none" xmlns="http://www.w3.org/2000/svg">
Ресурсы лучше называть по смыслу, а не по назначению. Не footerLogo, а blackWhiteLogo

2022-01-16 15:05 UTC, chervyakovru commented on src/Header/Header.jsx
> +  height: 30px;
![image](https://user-images.githubusercontent.com/14909082/149663450-dc5f812d-6a3b-4c55-9eaf-7a6498822f91.png)
![image](https://user-images.githubusercontent.com/14909082/149663455-10561fff-d6cb-4de2-824b-a38593b832d9.png)

На самом деле лого не квадратный

2022-01-16 15:05 UTC, chervyakovru commented on src/Header/Header.jsx
> +          <Nav />
Кажется margin-left остался в компоненте

2022-01-16 15:05 UTC, chervyakovru commented on src/Header/Nav.jsx
> +  color: black;
кажется тут не black

2022-01-16 15:05 UTC, chervyakovru commented on src/Header/Nav.jsx
> +  padding: 12px 0px;
не сработали padding потому что display: inline

2022-01-16 15:05 UTC, chervyakovru commented on src/Header/Nav.jsx
> +  font-weight: 400;
кажется такой вес по умолчанию

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Experiences/Experiences.jsx
> +const HeaderTitle = styled.div`
Header Title можно весь вынести в компонент чтобы seeAll каждый раз не писать

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Experiences/Experiences.jsx
> +const TittleTitle = styled.h5`
do u mean subTitle?)

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Experiences/Experiences.jsx
> +  column-gap: 17px;
Скорее всего тут также 18px как между всеми остальными колонками

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Experiences/Experiences.jsx
> +  overflow: hidden;
зачем тут overflow?

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Explore/Explore.jsx
> +  height: 100%;
тут хватит только height: 100%

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Explore/Explore.jsx
> +const StyledDescription = styled.p`
Можно не писать Styled. Просто Description

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Featured/Featured.jsx
> +const StyledFeatured = styled.div``;
не нужен styled

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Featured/Featured.jsx
> +import featuredOne from "./Featured.png";
featuredOne -> featured
Названия ресурсов лучше писать строчными буквами

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Featured/Featured.jsx
> +  column-gap: 17px;
18

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Featured/Featured.jsx
> +  overflow: hidden;
зачем hidden

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Homes/Homes.jsx
> +  overflow: hidden;
18 overflow

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Homes/Homes.jsx
> +const Column = styled.div``;
styled

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Homes/Homes.jsx
> +const TittleTitle = styled.h5`
subTitle

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Homes/Homes.jsx
> +  line-height: 18px;
Возможно во всем документе по умолчанию стоит сделать line-height 18?

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Main.jsx
> +  margin-bottom: 68px;
На самом деле между всеми ними по 48 px

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Popular/Popular.jsx
> +const Column = styled.div``;
styled

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Popular/Popular.jsx
> +  margin: 0px;
TT: uppercase

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Popular/Popular.jsx
> +  font-size: 12px;
fz: 10

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Popular/Popular.jsx
> +  font-weight: 400;
light

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Raiting/RatingLine.jsx
> +    // <React.Fragment>
remove comment

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Raiting/RatingLine.jsx
> +const ReviewsLine = styled.div`
styled не нужкен

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Raiting/RatingLine.jsx
> +  text-align: start;
text-alight нужен?

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/Raiting/RatingLine.jsx
> +export default function SeeAll() {
Кажется это не SeeAll

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/SectionSee/SectionSee.jsx
> +export default function SeeAll() {
лучше чтобы название файла и компоненте совпадали

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/SectionSee/SectionSee.jsx
> +const StyledSeeAll = styled.div`
зачем нужен этот div?

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/SectionSee/SectionSee.jsx
> +    z-index: 12;
почему 12? можно 1

2022-01-16 15:05 UTC, chervyakovru commented on src/Main/SectionSee/SectionSee.jsx
> +    left: 45px;
проще right: 0

2022-01-16 15:05 UTC, chervyakovru commented on src/Stub.jsx
> +  width: 100vw;
лучше задать в %. Если в 100vh, то будет скролится криво на мобилке

2022-01-16 15:05 UTC, chervyakovru commented on src/Stub.jsx
> +  backdrop-filter: blur(5px);
![image](https://user-images.githubusercontent.com/14909082/149665537-0f3e1421-b915-4e95-afa1-90af089615d3.png)
https://caniuse.com/?search=backdrop-filter

У backdrop-filter пока плохая поддержка. Лучше использовать что-то по проще

2022-01-16 15:05 UTC, chervyakovru commented on src/Stub.jsx
> +  font-family: "Circular Air Light";
Circular Air Light - не загружается такой шрифт

2022-01-16 15:05 UTC, chervyakovru commented on src/Stub.jsx
> +  font-family: "Circular Air Light";
И тут

2022-01-18 11:00 UTC, Poldyaich97 commented on src/Footer/Footer.jsx
> +  margin-bottom: 16px;
Почему убрать? это же отталкивает один select от другого
![image](https://user-images.githubusercontent.com/55269933/149924944-66d04a07-fb18-4fdb-98db-2eda5b73adb0.png)

2022-01-18 11:09 UTC, Poldyaich97 commented on src/Footer/Footer.jsx
> +  margin-bottom: 16px;
вопрос отпал

2022-01-18 11:11 UTC, Poldyaich97 commented on src/Stub.jsx
> +  width: 100vw;
в процентах наоборот съезжает..

2022-01-18 14:06 UTC, Poldyaich97 commented on src/Stub.jsx
> +  backdrop-filter: blur(5px);
![image](https://user-images.githubusercontent.com/55269933/149952414-c4a2b6a1-db45-4609-a132-add3e4771bde.png)
 DONE

2022-01-18 14:09 UTC, Poldyaich97 commented on src/Stub.jsx
> +  font-family: "Circular Air Light";
понять не могу почему у меня по всему проекту не работает шрифт.

2022-01-18 17:53 UTC, chervyakovru commented on src/Footer/Footer.jsx
> +  margin-bottom: 16px;
А коммент остался)

2022-01-18 18:33 UTC, chervyakovru commented on src/Fonts/@font-face/Demo.html
> +<!DOCTYPE html>
Все еще не нужен

2022-01-18 18:33 UTC, chervyakovru commented
> ![image](https://user-images.githubusercontent.com/14909082/149665005-e6306f84-4df4-44c7-835c-c0d3e9fb0308.png)
> 
> Картинка уже чем колонка

До сих пор уже

2022-01-18 18:34 UTC, chervyakovru commented
> Можно убрать папку @font-face

Все еще можно убрать

2022-01-18 18:35 UTC, chervyakovru commented
> ![image](https://user-images.githubusercontent.com/14909082/149662719-d679427a-3b5e-4cd1-abf2-cca2fc99e5b6.png) ![image](https://user-images.githubusercontent.com/14909082/149662746-0cbcfc67-68e5-4490-921b-bb07be740d8b.png)
> 
> Проект не запускается. Названия папок не соответствует

Все еще папка называется с большой буквы
![Uploading image.png…]()

2022-01-22 00:56 UTC, chervyakovru commented on src/Footer/footerLogo.svg
> +<svg width="21" height="22" viewBox="0 0 21 22" fill="none" xmlns="http://www.w3.org/2000/svg">
Остался footerLogo

2022-01-23 12:57 UTC, Poldyaich97 commented on src/Main/SectionSee/SectionSee.jsx
> +export default function SeeAll() {
SectionSee

2022-01-23 14:35 UTC, Poldyaich97 commented on src/Main/Experiences/Experiences.jsx
> +  column-gap: 17px;
по макету было 17. исправил

2022-01-23 14:36 UTC, Poldyaich97 commented on src/Main/Experiences/Experiences.jsx
> +const HeaderTitle = styled.div`
возможно, но seeall используется в 3 случаях  из 4

2022-01-29 14:43 UTC, Poldyaich97 commented on src/Main/SectionSee/SectionSee.jsx
> +    z-index: 12;
done

2022-01-29 14:43 UTC, Poldyaich97 commented on src/Main/SectionSee/SectionSee.jsx
> +const StyledSeeAll = styled.div`
done

2022-01-29 14:44 UTC, Poldyaich97 commented on src/Main/SectionSee/SectionSee.jsx
> +export default function SeeAll() {
done

2022-01-29 14:44 UTC, Poldyaich97 commented on src/Main/Raiting/RatingLine.jsx
> +export default function SeeAll() {
done

2022-01-29 14:45 UTC, Poldyaich97 commented on src/Main/Raiting/RatingLine.jsx
> +  text-align: start;
done

2022-01-29 14:45 UTC, Poldyaich97 commented on src/Main/Raiting/RatingLine.jsx
> +const ReviewsLine = styled.div`
done

2022-01-29 14:45 UTC, Poldyaich97 commented on src/Main/Raiting/RatingLine.jsx
> +    // <React.Fragment>
done

2022-01-29 14:46 UTC, Poldyaich97 commented on src/Main/Popular/Popular.jsx
> +  font-weight: 400;
done

2022-01-29 14:47 UTC, Poldyaich97 commented on src/Main/Popular/Popular.jsx
> +  font-size: 12px;
done

2022-01-29 14:47 UTC, Poldyaich97 commented on src/Main/Popular/Popular.jsx
> +  margin: 0px;
done

2022-01-29 14:48 UTC, Poldyaich97 commented on src/Main/Popular/Popular.jsx
> +const Column = styled.div``;
div

2022-01-29 14:48 UTC, Poldyaich97 commented on src/Main/Main.jsx
> +  margin-bottom: 68px;
done row-gap

2022-01-29 14:49 UTC, Poldyaich97 commented on src/Main/Homes/Homes.jsx
> +  line-height: 18px;
done

2022-01-29 14:49 UTC, Poldyaich97 commented on src/Main/Homes/Homes.jsx
> +const TittleTitle = styled.h5`
done

2022-01-29 14:49 UTC, Poldyaich97 commented on src/Main/Homes/Homes.jsx
> +const Column = styled.div``;
done

2022-01-29 14:50 UTC, Poldyaich97 commented on src/Main/Homes/Homes.jsx
> +  overflow: hidden;
done

2022-01-29 14:51 UTC, Poldyaich97 commented on src/Main/Featured/Featured.jsx
> +import featuredOne from "./Featured.png";
done

2022-01-29 14:51 UTC, Poldyaich97 commented on src/Main/Featured/Featured.jsx
> +const StyledFeatured = styled.div``;
done

2022-01-29 14:52 UTC, Poldyaich97 commented on src/Main/Explore/Explore.jsx
> +const StyledDescription = styled.p`
done

2022-01-29 14:53 UTC, Poldyaich97 commented on src/Main/Explore/Explore.jsx
> +  height: 100%;
done

2022-01-29 14:54 UTC, Poldyaich97 commented on src/Main/Experiences/Experiences.jsx
> +  overflow: hidden;
done

2022-01-29 14:55 UTC, Poldyaich97 commented on src/Main/Experiences/Experiences.jsx
> +  column-gap: 17px;
done

2022-01-29 14:55 UTC, Poldyaich97 commented on src/Main/Experiences/Experiences.jsx
> +const TittleTitle = styled.h5`
done

2022-01-29 14:56 UTC, Poldyaich97 commented on src/Main/Experiences/Experiences.jsx
> +const HeaderTitle = styled.div`
Мне кажется, что лучше  дополнительно его докидывать

2022-01-29 14:57 UTC, Poldyaich97 commented on src/Header/Nav.jsx
> +  font-weight: 400;
done

2022-01-29 14:57 UTC, Poldyaich97 commented on src/Header/Nav.jsx
> +  padding: 12px 0px;
done

2022-01-29 14:57 UTC, Poldyaich97 commented on src/Header/Nav.jsx
> +  color: black;
done

2022-01-29 14:59 UTC, Poldyaich97 commented on src/Header/Header.jsx
> +          <Nav />
тут не совсем понял?

2022-01-29 15:01 UTC, Poldyaich97 commented on src/Header/Header.jsx
> +  height: 30px;
done

2022-01-29 15:01 UTC, Poldyaich97 commented on src/Footer/footerLogo.svg
> +<svg width="21" height="22" viewBox="0 0 21 22" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-29 15:02 UTC, Poldyaich97 commented on src/Footer/Footer.jsx
> +  padding: 0;
done

2022-01-29 15:13 UTC, merged