Feature/gh pages
Poldyaich97/airbnb pull request #7
Opened 2022-03-18 12:13 UTC by Poldyaich97

2022-03-18 12:13 UTC, Poldyaich97 commented
done

2022-03-19 11:18 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/159118725-0a986698-a6eb-4ad3-95fa-be7a453da784.png)
![image](https://user-images.githubusercontent.com/14909082/159118739-b0b89c3b-2740-4518-8020-233a4c06c0f4.png)

2022-03-19 11:20 UTC, chervyakovru commented
Не стоит называть папки в разных регистрах. Все папки с компонентами должны начинаться с большой буквы
```
- hosts
- mobilStub (тут еще не хватает e в слове mobile)
```

2022-03-19 11:23 UTC, chervyakovru commented
Все слова в settings -> cSpell, кроме Salentina, не верные. Лучше их убрать и исправить в самом коде

2022-03-19 11:28 UTC, chervyakovru commented
Оставлять warning в консоли дурной тон

![image](https://user-images.githubusercontent.com/14909082/159119259-20465f86-bc8c-4297-93c4-796cd0a6daf4.png)

2022-03-19 11:29 UTC, chervyakovru commented
и в консоли браузера тоже

![image](https://user-images.githubusercontent.com/14909082/159119320-2f1e5bdf-79e5-40d1-b196-1a4e1a56eee5.png)

2022-03-19 11:48 UTC, chervyakovru requested changes

2022-03-19 11:48 UTC, chervyakovru commented on src/App.jsx
> +        {/* <StyledStub /> */}
Зачем закомментировал и оставил? Это нужно или нет?

2022-03-19 11:48 UTC, chervyakovru commented on src/App.jsx
> +    // display: none;
Зачем закомментировал и оставил? Это нужно или нет?

2022-03-19 11:48 UTC, chervyakovru commented on src/App.jsx
> +    // display: none;
Зачем закомментировал и оставил? Это нужно или нет?

2022-03-19 11:48 UTC, chervyakovru commented on src/App.jsx
> +import Hosts from "./hosts/Hosts";
Зачем переназвал директорию с маленькой буквы?

2022-03-19 11:48 UTC, chervyakovru commented on src/Footer/Footer.jsx
> +  @media (max-width: 700px) {
кажется не нужно

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Experiences/ExperiencesCard.jsx
> +    font-size: 12px;
подозрительно что вверху 2 раза размер шрифта меняется на 13px, а тут на 12. Скорее всего тут тоже нужен 13

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Explore/Explore.jsx
> +  width: 310px;
кажется можно не задавать им фиксированный размер. Почему решил задать?

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Explore/Explore.jsx
> +        {/* <Column>
Можно расскоментировать

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Featured/Featured.jsx
> +  } else if (window.innerWidth > 750) {
Кажется у тебя везде 700px

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Featured/Featured.jsx
> +  let NumCard;
переменные стоит называть с маленькой буквы

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Featured/Featured.jsx
> +  let NumCard;
- тут стоит заиспользовать switch case
- И вынести логику работы в отдельную функцию
- И подписаться на событие [resize](https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event) внутри хука useEffect, а cardNumber положить в state

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Homes/HomesCards.jsx
> +    font-size: 12px;
Нужно определиться с размером шрифта. 13 или 12. И везде заменить на него

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Popular/Popular.jsx
> +  let NumCard;
Возможно, стоит переиспользовать функцию из других компонентов

2022-03-19 11:48 UTC, chervyakovru commented on src/Main/Featured/Featured.jsx
> +    console.log(NumCard);
console.log не должны оставаться в коде

2022-03-19 11:58 UTC, chervyakovru commented
Visual bugs:
яяя
![image](https://user-images.githubusercontent.com/14909082/159120023-75dc468a-36b1-4ca4-a903-2681009c7581.png)

ччч
![image](https://user-images.githubusercontent.com/14909082/159120135-40910a14-4578-4958-9efd-6861e91bd4c9.png)

Лишнее значение по умолчанию
![image](https://user-images.githubusercontent.com/14909082/159120170-ceb5e7b9-7b56-468c-9ded-155740fac6cf.png)

2022-03-19 12:04 UTC, chervyakovru commented
Баги адаптивности:
![image](https://user-images.githubusercontent.com/14909082/159120230-6767bd0d-c3f6-4055-83da-abc28899dfaf.png)
![image](https://user-images.githubusercontent.com/14909082/159120286-505ba0f7-7460-466b-9705-545370edb215.png)
![image](https://user-images.githubusercontent.com/14909082/159120263-3ed8b07e-f522-4a53-8c4d-193c064a7ffd.png)
![image](https://user-images.githubusercontent.com/14909082/159120314-c281bef0-c94b-4ddf-a156-a126ed96b7c6.png)
![image](https://user-images.githubusercontent.com/14909082/159120324-31e0abb5-9b80-4ff8-97da-37b98a93aa03.png)

2022-03-21 13:10 UTC, Poldyaich97 commented on src/App.jsx
> +        {/* <StyledStub /> */}
Уже не нужно

2022-03-21 13:13 UTC, Poldyaich97 commented on src/App.jsx
> +import Hosts from "./hosts/Hosts";
Честно, не менял.

2022-03-21 13:14 UTC, Poldyaich97 commented on src/Footer/Footer.jsx
> +  @media (max-width: 700px) {
Почему не нужно? в мобильной версии этого блока нет вообще

2022-03-21 14:08 UTC, Poldyaich97 commented on src/Main/Featured/Featured.jsx
> +  } else if (window.innerWidth > 750) {
не верно. на 750 исправил. макет чекнул

2022-03-28 17:57 UTC, chervyakovru commented on src/Footer/Footer.jsx
> +  @media (max-width: 750px) {
Пустой

2022-03-28 18:09 UTC, chervyakovru approved these changes

2022-04-04 19:07 UTC, merged